In [1]:
%matplotlib inline

# 필요한 라이브러리 로딩
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# 메모장으로 열어보면 오른쪽아래에 데이터형식이 ANSI로 되어있음
# utf-8로 인코딩해도 에러생김 (UnicodeDecodeError)

In [6]:
# 데이터 로딩
crime = pd.read_csv('D:/python3/data/crime_in_Seoul.csv', encoding='euc-kr')
crime.head()

    관서명  살인 발생  살인 검거  강도 발생  강도 검거  강간 발생  강간 검거  절도 발생 절도 검거  폭력 발생  폭력 검거
0   중부서      2      2      3      2    105     65  1,395   477  1,355  1,170
1   종로서      3      3      6      5    115     98  1,070   413  1,278  1,070
2  남대문서      1      0      6      4     65     46  1,153   382    869    794
3  서대문서      2      2      5      4    154    124  1,812   738  2,056  1,711
4   혜화서      3      2      5      4     96     63  1,114   424  1,015    861

In [7]:
# 데이터 확인
crime.shape

(31, 11)

In [8]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
관서명      31 non-null object
살인 발생    31 non-null int64
살인 검거    31 non-null int64
강도 발생    31 non-null int64
강도 검거    31 non-null int64
강간 발생    31 non-null int64
강간 검거    31 non-null int64
절도 발생    31 non-null object
절도 검거    31 non-null object
폭력 발생    31 non-null object
폭력 검거    31 non-null object
dtypes: int64(6), object(5)
memory usage: 2.7+ KB

In [9]:
crime.columns

Index(['관서명', '살인 발생', '살인 검거', '강도 발생', '강도 검거', '강간 발생', '강간 검거', '절도 발생',
       '절도 검거', '폭력 발생', '폭력 검거'],
      dtype='object')

In [10]:
crime.index

RangeIndex(start=0, stop=31, step=1)

In [11]:
# 정량적 데이터의 기초통계분석
crime.describe()

           살인 발생      살인 검거      강도 발생      강도 검거       강간 발생       강간 검거
count  31.000000  31.000000  31.000000  31.000000   31.000000   31.000000
mean    5.258065   4.935484   8.903226   8.161290  175.774194  131.967742
std     3.605253   3.203493   4.935280   5.710206   85.580259   56.590037
min     1.000000   0.000000   1.000000   1.000000   59.000000   46.000000
25%     3.000000   2.500000   6.000000   4.000000  103.500000   90.000000
50%     4.000000   4.000000   8.000000   7.000000  154.000000  124.000000
75%     7.500000   7.500000  13.000000  11.500000  251.000000  175.500000
max    14.000000  12.000000  22.000000  26.000000  334.000000  247.000000

In [ ]:
# 피벗 = 축

In [ ]:
# pandas의 pivot_table

In [12]:
crime

     관서명  살인 발생  살인 검거  강도 발생  강도 검거  강간 발생  강간 검거  절도 발생  절도 검거  폭력 발생  폭력 검거
0    중부서      2      2      3      2    105     65  1,395    477  1,355  1,170
1    종로서      3      3      6      5    115     98  1,070    413  1,278  1,070
2   남대문서      1      0      6      4     65     46  1,153    382    869    794
3   서대문서      2      2      5      4    154    124  1,812    738  2,056  1,711
4    혜화서      3      2      5      4     96     63  1,114    424  1,015    861
5    용산서      5      5     14     14    194    173  1,557    587  2,050  1,704
6    성북서      2      2      2      1     86     71    953    409  1,194  1,015
7   동대문서      5      5     13     13    173    146  1,981    814  2,548  2,227
8    마포서      8      8     14     10    294    247  2,555    813  2,983  2,519
9   영등포서     14     12     22     20    295    183  2,964    978  3,572  2,961
10   성동서      4      4      9      8    126    119  1,607    597  1,612  1,395
11   동작서      5      5      9      5    285    139  1,865    661  1,910  1,587
12   광진서      4      4     14     26    240    220  3,026  1,277  2,625  2,180
13   서부서      2      2      2      1     70     59    819    293  1,192  1,038
14   강북서      7      8     14     13    153    126  1,434    618  2,649  2,348
15   금천서      3      4      6      6    151    122  1,567    888  2,054  1,776
16   중랑서     13     12     11      9    187    148  2,135    829  2,847  2,407
17   강남서      3      3     15     12    300    225  2,411    984  2,465  2,146
18   관악서      9      8     12     14    320    221  2,706    827  3,298  2,642
19   강서서      7      8     13     13    262    191  2,096  1,260  3,207  2,718
20   강동서      4      3      6      8    156    123  2,366    789  2,712  2,248
21   종암서      3      3      3      3     64     53    832    332  1,015    840
22   구로서      8      6     15     11    281    164  2,335    889  3,007  2,432
23   서초서      7      4      8      5    334    193  1,982    905  1,852  1,607
24   양천서      3      5      6      3    120    105  1,890    672  2,509  2,030
25   송파서     11     10     13     10    220    178  3,239  1,129  3,295  2,786
26   노원서     10     10      7      7    197    121  2,193    801  2,723  2,329
27   방배서      1      2      1      1     59     56    653    186    547    491
28   은평서      1      1      7      5     96     82  1,095    418  1,461  1,268
29   도봉서      3      3      9     10    102    106  1,063    478  1,487  1,303
30   수서서     10      7      6      6    149    124  1,439    666  1,819  1,559

In [15]:
crime_anal_raw = pd.read_csv('D:/python3/data/crime_in_Seoul_include_gu_name.csv', encoding='utf-8')
crime_anal_raw.head()

,Unnamed: 0,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,2,남대문서,1,0,6,4,65,46,1153,382,869,794,중구
3,3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구

In [16]:
crime_anal_raw.shape

(31, 13)

In [17]:
crime_anal_raw

,Unnamed: 0,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,2,남대문서,1,0,6,4,65,46,1153,382,869,794,중구
3,3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구
5,5,용산서,5,5,14,14,194,173,1557,587,2050,1704,용산구
6,6,성북서,2,2,2,1,86,71,953,409,1194,1015,성북구
7,7,동대문서,5,5,13,13,173,146,1981,814,2548,2227,동대문구
8,8,마포서,8,8,14,10,294,247,2555,813,2983,2519,마포구
9,9,영등포서,14,12,22,20,295,183,2964,978,3572,2961,영등포구
10,10,성동서,4,4,9,8,126,119,1607,597,1612,1395,성동구
11,11,동작서,5,5,9,5,285,139,1865,661,1910,1587,동작구
12,12,광진서,4,4,14,26,240,220,3026,1277,2625,2180,광진구
13,13,서부서,2,2,2,1,70,59,819,293,1192,1038,은평구
14,14,강북서,7,8,14,13,153,126,1434,618,2649,2348,강북구
15,15,금천서,3,4,6,6,151,122,1567,888,2054,1776,금천구
16,16,중랑서,13,12,11,9,187,148,2135,829,2847,2407,중랑구
17,17,강남서,3,3,15,12,300,225,2411,984,2465,2146,강남구
18,18,관악서,9,8,12,14,320,221,2706,827,3298,2642,관악구
19,19,강서서,7,8,13,13,262,191,2096,1260,3207,2718,양천구
20,20,강동서,4,3,6,8,156,123,2366,789,2712,2248,강동구
21,21,종암서,3,3,3,3,64,53,832,332,1015,840,성북구
22,22,구로서,8,6,15,11,281,164,2335,889,3007,2432,구로구
23,23,서초서,7,4,8,5,334,193,1982,905,1852,1607,서초구
24,24,양천서,3,5,6,3,120,105,1890,672,2509,2030,양천구
25,25,송파서,11,10,13,10,220,178,3239,1129,3295,2786,송파구
26,26,노원서,10,10,7,7,197,121,2193,801,2723,2329,노원구
27,27,방배서,1,2,1,1,59,56,653,186,547,491,서초구
28,28,은평서,1,1,7,5,96,82,1095,418,1461,1268,은평구
29,29,도봉서,3,3,9,10,102,106,1063,478,1487,1303,도봉구
30,30,수서서,10,7,6,6,149,124,1439,666,1819,1559,강남구

In [19]:
# 관서별에서 구별로 바꿔서 데이터를 정리
crime_anal_raw = pd.read_csv('D:/python3/data/crime_in_Seoul_include_gu_name.csv',
                             encoding='utf-8', index_col=0)
# 피벗테이블
crime_anal_raw = pd.pivot_table(crime_anal_raw, index='구별', aggfunc=np.sum)
crime_anal_raw.head()        # aggregation?_func 집합함수 - 동일한 구별끼리 합침(sum)

     강간 검거  강간 발생  강도 검거  강도 발생  살인 검거  살인 발생  절도 검거  절도 발생  폭력 검거  폭력 발생
구별
강남구    349    449     18     21     10     13   1650   3850   3705   4284
강동구    123    156      8      6      3      4    789   2366   2248   2712
강북구    126    153     13     14      8      7    618   1434   2348   2649
관악구    221    320     14     12      8      9    827   2706   2642   3298
광진구    220    240     26     14      4      4   1277   3026   2180   2625

In [ ]:
# 검거율 (강간,강도,살인,절도,폭력)